services:
  signal:
    build: ./signal
    ports:
      - "${SIGNAL_PORT}:${SIGNAL_PORT}"
    environment:
      SIGNAL_PORT: ${SIGNAL_PORT}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      SUPABASE_URL: ${SUPABASE_URL}
    networks:
      - cloud-gaming

networks:
  cloud-gaming:
    name: cloud-gaming