services:
  signal:
    build:
      context: .
      dockerfile: signal/Dockerfile

    ports:
      - "${SIGNAL_PORT}:${SIGNAL_PORT}"
    environment:
      WORKER_PASSWORD: ${WORKER_PASSWORD}
      SIGNAL_PORT: ${SIGNAL_PORT}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      SUPABASE_URL: ${SUPABASE_URL}
      CLOUDFLARE_TURN_KEY_ID: ${CLOUDFLARE_TURN_KEY_ID}
      CLOUDFLARE_TURN_API_TOKEN: ${CLOUDFLARE_TURN_API_TOKEN}
