apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gaming

resources:
  - ../../base
  - nodepool.yaml  # Only needed in prod (EKS Auto Mode)

# ECR images - replace with your account ID
images:
  - name: signal
    newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/android-cloud-gaming/signal
    newTag: latest

patches:
  # Production replicas
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: signal-server

  # Add production environment variables
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: NODE_ENV
          value: production
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: WORKER_IMAGE
          value: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/android-cloud-gaming/worker:latest
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: REDROID_IMAGE
          value: redroid/redroid:12.0.0-latest
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: WARM_POOL_SIZE
          value: "3"
    target:
      kind: Deployment
      name: signal-server
