blank_issues_enabled: false
contact_links:
  - name: Questions / Discussion
    url: https://github.com/maddox05/android-cloud-gaming/discussions
    about: Use Discussions for questions or general chat
