apiVersion: v1
kind: ServiceAccount
metadata:
  name: signal-server
  namespace: gaming
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-manager
  namespace: gaming
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: signal-pod-manager
  namespace: gaming
subjects:
  - kind: ServiceAccount
    name: signal-server
    namespace: gaming
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io
